// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoTouchTinyIoCPlatformTests {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UITextView __mt_results;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("buttonClick:")]
		partial void buttonClick (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("results")]
		private MonoTouch.UIKit.UITextView results {
			get {
				this.__mt_results = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("results")));
				return this.__mt_results;
			}
			set {
				this.__mt_results = value;
				this.SetNativeField("results", value);
			}
		}
	}
}
